# Generated by Django 2.2.10 on 2021-12-09 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_auto_20211209_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='user_quiz',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_quiz', to='polls.Quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userquiz',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
