# Generated by Django 2.2.10 on 2021-12-09 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211209_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='accounts.UserProfile'),
        ),
    ]
