# Generated by Django 2.2.10 on 2021-12-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211209_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='question_for_answer', to='polls.Question'),
            preserve_default=False,
        ),
    ]
