# Generated by Django 2.2.10 on 2021-12-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quiz',
            new_name='user_quiz',
        ),
    ]
